# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
#cache: packages
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - mesa-common-dev
      - libglu1-mesa-dev

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="release build"
        - os: osx
          r: release
        #  disable_homebrew: true
          env:
           - BUILD_NAME=osx_release
           - DETAILS="osx_release build"

after_success:
  - Rscript -e 'covr::codecov()'

